### ISSUE TITLE
Can't use HasMany and BelongsTo at the same time

### ISSUE THREAD

**Issue by Bricklou** [kerwanp/adonis-cockpit#24]
I have 2 resources : `GameResources` and `CreatorResources`.

- `GameResources` have a `BelongsTo` field refering to the `CreatorResource`.
- `CreatorResources` have a `HasMany` field refering to the `GameResources`

When asking for `CreatorResources.fields()`, i get the following error:
```
Cannot read properties of undefined (reading 'type')

[20:21:21.762] ERROR (1231264): Cannot read properties of undefined (reading 'type')
    request_id: "s1ej9fta48uvj7zi37bbmrpi"
    x-request-id: "s1ej9fta48uvj7zi37bbmrpi"
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'type')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'type')
              at make (.../packages/website/extensions/cockpit/fields/has_many.ts:56:22)
              at fields (.../packages/website/app/cockpit/resources/creator_resource.ts:25:15)
              at toJSON (.../packages/website/app/cockpit/resources/creator_resource.ts:33:20)
              at toJSON (.../packages/website/extensions/cockpit/fields/belongs_to.ts:61:32)
              at <anonymous> (.../packages/website/extensions/cockpit/resources/base_resource.ts:129:70)
              at Array.map (<anonymous>)
              at <anonymous> (.../packages/website/extensions/cockpit/resources/base_resource.ts:129:49)
              at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
              at toJSON (.../packages/website/extensions/cockpit/resources/base_resource.ts:115:33)
              at toJSON (.../packages/website/extensions/cockpit/fields/has_many.ts:75:32)
      "status": 500
    }
```
![image](https://github.com/user-attachments/assets/2936a168-cbac-489d-8f86-c7fa0a18eb93)

(PS: since the dashboard currently only support Vue, I just copied adonis-cockpit files inside my project to make things work, the whole behaviour hasn't changed)

**Comment by Bricklou** [comment]
It seems I made some mistakes in my own code, I managed to fix the issue.
